apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-controller
  template:
    metadata:
      labels:
        app: k8s-controller
    spec:
      serviceAccountName: k8s-controller
      containers:
        - name: k8s-controller-container
          image: k8s-controller:1.0 # Replace with your image details
          command: ["python", "k8s_controller.py"] # Replace with your Python script filename
          env:
            - name: LOG_LEVEL
              value: "INFO" # Set your desired log level
            - name: TEAMS_URL
              value: "your_teams_url_value" # Replace with your Teams URL value
            - name: NAMESPACE
              value: "default" # Replace with your Namespace value
            - name: INTERVAL
              value: "30" # Set your desired interval value (default: 30 seconds)
      restartPolicy: Always