apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-controller
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-patcher
rules:
- apiGroups: ["apps"]  # Deployments are in the "apps" API group
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-patcher-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: k8s-controller
  namespace: default
roleRef:
  kind: Role
  name: deployment-patcher
  apiGroup: rbac.authorization.k8s.io